version: 2.1

jobs:
  build:
    docker:
      - image: gcc:latest
    steps:
      - checkout
      - run: gcc -o main main.c  # Compiling main code
      - run: ./main  # Running main code
      - run: gcc -o test_scheduler test_scheduler.c scheduler.c unity.c  # Compiling test code
      - run: ./test_scheduler  # Running test code

workflows:
  build_and_test:
    jobs:
      - build
