version: 2.1

jobs:
  build:
    docker:
      - image: gcc:latest
    steps:
      - checkout
      - run: gcc -o main main.c  # Compiling main code
      - run: ./main  # Running main code
      - run: gcc -o test_schedule test_scheduler.c scheduler.c unity.c -I.  # add -I. to include the current directory
      - run: ./test_scheduler  # Running test code

workflows:
  build_and_test:
    jobs:
      - build
