version: 2.1

jobs:
  build:
    docker:
      - image: gcc:latest
    steps:
      - checkout
      - run: gcc -o main main.c  # Compiling main code along with scheduler.c
      - run: ./main  # Running main code
      - run: gcc -o test_schedule test_schedule.c schedule.c unity.c  # Compiling test code along with scheduler.c and unity.c
      - run: ./test_schedule  # Running test code

workflows:
  build_and_test:
    jobs:
      - build
